### ISSUE TITLE
`go get -u` timing out 😢 

### ISSUE THREAD

**Issue by tommed** [microsoftgraph/msgraph-sdk-go#142]
I have a relatively empty library which encapsulates/abstracts the azure ad sdk. On my machine, `go get -u` and `go mod tidy` time-out after about 5mins during the fetching of dependencies.

To make use of this library, the following dependencies were needed (full go.mod):

```
module github.com/vigilant-go/azuread

go 1.18

require (
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.14.0
	github.com/microsoft/kiota-authentication-azure-go v0.1.0
	github.com/microsoftgraph/msgraph-sdk-go v0.19.0
	github.com/microsoftgraph/msgraph-sdk-go-core v0.22.0
	github.com/pkg/errors v0.9.1
	github.com/stretchr/testify v1.7.1
	github.com/youmark/pkcs8 v0.0.0-20181117223130-1be2e3e5546d
	golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
)

require (
	github.com/Azure/azure-sdk-for-go/sdk/azcore v0.23.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/internal v0.9.1 // indirect
	github.com/AzureAD/microsoft-authentication-library-for-go v0.4.0 // indirect
	github.com/cjlapao/common-go v0.0.19 // indirect
	github.com/davecgh/go-spew v1.1.1 // indirect
	github.com/golang-jwt/jwt v3.2.2+incompatible // indirect
	github.com/google/uuid v1.3.0 // indirect
	github.com/kylelemons/godebug v1.1.0 // indirect
	github.com/microsoft/kiota-abstractions-go v0.4.0 // indirect
	github.com/microsoft/kiota-http-go v0.3.0 // indirect
	github.com/microsoft/kiota-serialization-json-go v0.3.0 // indirect
	github.com/microsoft/kiota-serialization-text-go v0.2.0 // indirect
	github.com/pkg/browser v0.0.0-20210911075715-681adbf594b8 // indirect
	github.com/pmezard/go-difflib v1.0.0 // indirect
	github.com/yosida95/uritemplate/v3 v3.0.2 // indirect
	golang.org/x/net v0.0.0-20220420153159-1850ba15e1be // indirect
	golang.org/x/sys v0.0.0-20220412211240-33da011f77ad // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)
```

It's not related to my machine, as this even happens on GitHub Actions (every time):

```yaml
name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: go build .

      - name: Test
        run: go test -v ./...
```

6ms to fetch dependencies 😢 :

![Screenshot 2022-04-22 at 09 02 56](https://user-images.githubusercontent.com/13066/164645055-ec5d886a-0ce6-49cf-96f0-8d90f5dbb5b1.png)

This started happening yesterday if that helps?
